Support --with-model=medium and --with-model=large

diff --git a/gcc-build b/gcc-build
--- a/gcc-build
+++ b/gcc-build
@@ -7,6 +7,18 @@ ARCH=$(arch)
 OPTION=
 while [ 1 = 1 ]; do
   case x"${1}" in
+  x--with-model=medium)
+    MEDIUM_MODEL=yes
+    MODEL=medium
+    OPTION=${OPTION}.medium
+    shift
+    ;;
+  x--with-model=large)
+    LARGE_MODEL=yes
+    MODEL=large
+    OPTION=${OPTION}.large
+    shift
+    ;;
   x--with-pic)
     PIC=yes
     OPTION=${OPTION}.pic
@@ -43,6 +55,7 @@ while [ 1 = 1 ]; do
       ;;
     *)
       echo $0: Unknown option: $1
+      exit 1
       ;;
     esac
     shift
@@ -63,6 +76,17 @@ while [ 1 = 1 ]; do
 done
 
 . ./gcc.options
+
+if [ -n "$MEDIUM_MODEL$LARGE_MODEL" ]; then
+  if [ x"$MEDIUM_MODEL$LARGE_MODEL" = xyesyes ]; then
+    echo "--with-model=medium --with-model=large cannot be used together"
+    exit 1
+  fi
+  if [ x"$ARCH" = xi686 -o x"$ENABLE_X32" = xyes ]; then
+    echo "--with-model=$MODEL cannot be with i686 or x32"
+    exit 1
+  fi
+fi
 
 trap 'rm -f lock; exit 1' 1 2 12 15
 
@@ -124,6 +148,7 @@ case $STATUS in
   make ARCH=$ARCH one-$GCC CONFIG_FLAGS="$CONFIG_FLAGS" \
        ENABLE_X32=$ENABLE_X32 \
        PIC=$PIC \
+       MODEL=$MODEL \
        CURRENT_LOG=$CURRENT_LOG > $CURRENT_LOG 2>&1
   STATUS=$?
   if [ $STATUS = 0 ]; then
